### PR TITLE
Support for viewing multiple PDFs 

### LINKED ISSUE #10: [Bug]: Upload multiple PDFs and only shows one of them in the viewer
### What happened?

I currently have a `FileUpload` form where a user can upload a PDF file. When I upload the first PDF file, the PDF shows in the preview. When I upload a second PDF and then save, I don't see the second PDF in the view.

### How to reproduce the bug

This is the code I added:

```php
FileUpload::make('document_management')
    ->panelLayout('grid')
    ->previewable()
    ->multiple(),

PdfViewerField::make('document_management')
    ->label('View the PDF')
    ->minHeight('40svh'),
  ```

Here is an example:

https://github.com/user-attachments/assets/6c169bcb-3a6f-4926-9a6a-75ae571df3ed

### Package Version

v1.0.5

### PHP Version

v8.3.11

### Laravel Version

v11.23.5

### Which operating systems does with happen with?

macOS

### Notes

_No response_

### PR DESCRIPTION
**Pull request by DevShaded**
This pull request allows viewing multiple PDFs at once, for both info list and forms.

**In Forms**
image

**In Infolist**
image

Closes #10

### CODE REVIEW

**Comment by joaopaulolndev** [comment]
@DevShaded Sorry, man, I'm on holiday without a computer to do tests.
I will go back to having a computer just on October 15.

**Comment by DevShaded** [comment]
I apologize, I didn't know you were on holiday. I can't wait to hear your thoughts! Wishing you a wonderful rest of your vacation!

**Comment by joaopaulolndev** [comment]
@DevShaded  no problem man, I will try to test this feature asap when have a PC.

**Comment by DevShaded** [comment]
Due to inactivity, closed.

**Pull request closed without merging**
